### ISSUE TITLE
Bug happening：the “Overrepresented_Sequences.csv” is empty

### ISSUE THREAD

**Issue by GMinghui** [pnnl/fqc#1]
When the Overrepresented Sequences field is "PASS",the "Overrepresented_Sequences.csv” will be  empty,and cause the bug :"KeyErrors:"Overrepresented_Sequences.csv"
What can I do to repair the bug? 
Thanke you !

**Comment by brwnj** [comment]
Update to 1.5.5 and see if this persists. If so, please send the full error and I'll get it sorted out.

**Comment by GMinghui** [comment]
commd:  `fqc qc  test_Group test_sample test.R2.fq.gz  ` is OK .
But : 
```
commd : fqc qc --r2 test.R2.fq.gz test_Group test_sample test.R1.fq.gz  
>>>
[2017-06-21 03:54 INFO] Writing data to: /work/user/gemh/Tools/fqc-master/test/plot_data/test_Group/test_sample
[2017-06-21 03:54 INFO] Running FastQC
[2017-06-21 03:55 INFO] Extracting data from FastQC archives
Traceback (most recent call last):
  File "/home/anaconda3/bin/fqc", line 11, in <module>
    load_entry_point('fqc==1.5.5', 'console_scripts', 'fqc')()
  File "/home/anaconda3/lib/python3.6/site-packages/fqc-1.5.5-py3.6.egg/fqc/fqc.py", line 322, in main
  File "/home/anaconda3/lib/python3.6/site-packages/fqc-1.5.5-py3.6.egg/fqc/fqc.py", line 47, in run_qc
  File "/home/gemh/anaconda3/lib/python3.6/site-packages/fqc-1.5.5-py3.6.egg/fqc/fastqc.py", line 242, in run
  File "/home/gemh/anaconda3/lib/python3.6/site-packages/fqc-1.5.5-py3.6.egg/fqc/fastqc.py", line 113, in extract_data
  File "/home/gemh/anaconda3/lib/python3.6/site-packages/fqc-1.5.5-py3.6.egg/fqc/fastqc.py", line 79, in file_and_status_from_metarow
KeyError: 'Overrepresented_sequences.csv'
```
The same error,whenthe "Overrepresented Sequences" field is "PASS",the "Overrepresented_Sequences.csv” will be empty,and cause the bug :"KeyErrors:"Overrepresented_Sequences.csv"
Thanke you very much!!

**Comment by brwnj** [comment]
I added an option to `fqc qc` called `--keep-tmp` that could help debugging in the future. I couldn't reproduce this exact error, but it looks like FastQC will omit some statistics altogether for one of either R1 or R2. In your issue, R1 must not have an entry in the fastqc_data file for overrepresented sequences.

Hopefully version 1.5.6 fixes this for you. Thanks for the feedback.

**Comment by GMinghui** [comment]
Problem solved .
Nice program.
Thanks
